### ISSUE TITLE
请问istio-pilot配置全量下发到sidecar，有解决方案吗

### ISSUE THREAD

**Issue by pretty66** [champly/mcpserver#1]
> istio xds协议相关的推送，目前cds、lds都是全量推送的，看了istio源码增量推送的功能暂时还不支持，想问下你们在使用istio的时候对这方面有优化吗。

> 例如：k8s集群已经部署了2000个服务，当部署第2001个时，这个服务在启动时，会去istio-pilot拉取之前的2000个服务的cds、lds信息，并且istio会给之前的2000个服务推送xds全量更新！

想问下针对这种大集群，xds数据推送的问题是怎么优化的

**Comment by champly** [comment]
> > istio xds协议相关的推送，目前cds、lds都是全量推送的，看了istio源码增量推送的功能暂时还不支持，想问下你们在使用istio的时候对这方面有优化吗。
> 
> > 例如：k8s集群已经部署了2000个服务，当部署第2001个时，这个服务在启动时，会去istio-pilot拉取之前的2000个服务的cds、lds信息，并且istio会给之前的2000个服务推送xds全量更新！
> 
> 想问下针对这种大集群，xds数据推送的问题是怎么优化的

通过创建Sidecar来下发需要的配置，具体信息可以查看[sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/)

**Comment by pretty66** [comment]
> 通过创建Sidecar来下发需要的配置，具体信息可以查看[sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/)

好的，我学习下看看，感谢 :+1:

**Comment by violin-debug** [comment]
> > > istio xds协议相关的推送，目前cds、lds都是全量推送的，看了istio源码增量推送的功能暂时还不支持，想问下你们在使用istio的时候对这方面有优化吗。
> > 
> > 
> > > 例如：k8s集群已经部署了2000个服务，当部署第2001个时，这个服务在启动时，会去istio-pilot拉取之前的2000个服务的cds、lds信息，并且istio会给之前的2000个服务推送xds全量更新！
> > 
> > 
> > 想问下针对这种大集群，xds数据推送的问题是怎么优化的
> 
> 通过创建Sidecar来下发需要的配置，具体信息可以查看[sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/)

请问创建完Sidecar（CR）后，Pilot是可以按需下发了吗？怎么查看pilot具体下发的东西是什么呢？

**Comment by champly** [comment]
> > > > istio xds协议相关的推送，目前cds、lds都是全量推送的，看了istio源码增量推送的功能暂时还不支持，想问下你们在使用istio的时候对这方面有优化吗。
> > > 
> > > 
> > > > 例如：k8s集群已经部署了2000个服务，当部署第2001个时，这个服务在启动时，会去istio-pilot拉取之前的2000个服务的cds、lds信息，并且istio会给之前的2000个服务推送xds全量更新！
> > > 
> > > 
> > > 想问下针对这种大集群，xds数据推送的问题是怎么优化的
> > 
> > 
> > 通过创建Sidecar来下发需要的配置，具体信息可以查看[sidecar](https://istio.io/latest/docs/reference/config/networking/sidecar/)
> 
> 请问创建完Sidecar（CR）后，Pilot是可以按需下发了吗？怎么查看pilot具体下发的东西是什么呢？

`sidecar` 创建之后，确实可以按需下发，具体的配置查看的话可以在对应的数据面倒出配置来进行查看，下发可能会有一定的延迟.

**Comment by Erchoc** [comment]
截至目前 istio v1.14，增量 xDS 订阅接口在 Pilot 中还未实现

**Comment by CYFWLP67373** [comment]
请问如果我想默认istio-pilot默认不下发配置，是否只能修改源码？

> 截至目前 istio v1.14，增量 xDS 订阅接口在 Pilot 中还未实现
